### ISSUE TITLE
Compression does not work in IE and Firefox for default settings

### ISSUE THREAD

**Issue by corporatepiyush** [ziplet/ziplet#12]
I have included this library in spring 4 mvc project. while i try to access the web app all HTTP response is getting compressed in case of chrome 44.0, but when i try to access it from IE 11 or FF32, it does not compress any response ?

I am using default settings.

**Comment by fededonna** [comment]
Can you send the config you are using? Could you be filtering by user agent?

**Comment by corporatepiyush** [comment]
I am not providing any extra config. So just using what is supported by default.

**Comment by fgaule** [comment]
Could you try our new version 2.1.2 ?

**Comment by corporatepiyush** [comment]
Thanks 👍
