### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by dlandis** [ziplet/ziplet#15]
Hi,

I was just wondering if you were going to do a new release soon. It looks like it's been a couple years since the last official release and that one has some issues that might prevent me from using it.

Thanks

**Comment by fgaule** [comment]
Hi. We are waiting some feedback for issue #6 to build next release

**Comment by kbrazulewicz** [comment]
Would love to see that new release soon :)

**Comment by jgoldhammer** [comment]
Any update here?
Thanks,
Jens

**Comment by fgaule** [comment]
I wil try to make a realese this week. Stay tunned!

**Comment by fgaule** [comment]
Version 2.1.2 has been released

**Comment by jgoldhammer** [comment]
Thanks...
