### ISSUE TITLE
Ziplet grabs Java8 compiled dependency

### ISSUE THREAD

**Issue by IuriiSergiichuk** [ziplet/ziplet#31]
Hi,

I'm using ziplet in my web-application, that is gonna be deployed on AppEngine standard, Java7. And with latest update, I have found impossible to deploy the app, cause now, I've got additional dependency in my Gradle dependency tree from the `com.github.ziplet:ziplet:2.3.0`:

```
+--- com.github.ziplet:ziplet:[2.3.0] -> 2.3.0
|    +--- com.google.googlejavaformat:google-java-format:1.4
|    |    +--- com.google.guava:guava:19.0 -> 20.0
|    |    \--- com.google.errorprone:javac-shaded:9-dev-r4023-3
|    \--- org.slf4j:slf4j-api:1.7.6 -> 1.7.25
```

And here are dependencies grabbed from `com.github.ziplet:ziplet:2.2.0`:
```
+--- com.github.ziplet:ziplet:[2.2.0] -> 2.2.0
|    \--- org.slf4j:slf4j-api:1.7.6 -> 1.7.25
```

I've already had issues with `errorprone` compiler and Java7 compatibility, so as for now I'd probably downgrade the version.

In order to fix the problem, probably, you have to adjust `google-java-format` scope within your `pom.xml`, shouldn't it be `provided`?

**Comment by fgaule** [comment]
Have you tried excluding google-java-format in version 2.3.0 as a workaround?

**Comment by IuriiSergiichuk** [comment]
@fgaule Nope, cause I haven't looked whether it's important for the project or not.

Looks like it's just used to cleanup/format code, so, probably, exclusion should help.

But, IMO, it's not a correct way to handle dependencies.

**Comment by fgaule** [comment]
I agree its not the corerct way, but i'm trying to help you to deploy :)
It will be fix for next release, but for sure won't be in the next days

**Comment by IuriiSergiichuk** [comment]
@fgaule OK. I can use previous version for now.

Thanks for taking this in account.
