### ISSUE TITLE
Ziplet is downloading older guava package

### ISSUE THREAD

**Issue by druveen** [ziplet/ziplet#34]
Ziplet is downloading older guava package 19. Looks like it has some issues.
Latest version of guava is >26

 com.github.ziplet:ziplet:jar:2.3.0:compile
[INFO]    \- com.google.googlejavaformat:google-java-format:jar:1.4:compile
[INFO]       +- com.google.guava:guava:jar:19.0:compile
[INFO]       \- com.google.errorprone:javac-shaded:jar:9-dev-r4023-3:compile

Any plan to upgade ziplet to download latest guava package.

**Comment by stuartraetaylor** [comment]
It looks like this issue was fixed by excluding google-java-format as a dependency in #32, but that fix isn't included in the latest release.

@fgaule any chance of creating a new release that includes the fix?

For now there's a workaround described in #31.

Cheers,
Stuart.

**Comment by fgaule** [comment]
Released in version 2.4.0
