### ISSUE TITLE
Tomcat 8 support

### ISSUE THREAD

**Issue by amasson88** [ziplet/ziplet#6]
Hi

Is Tomcat 8 supported?
I have long delay for gzipped static resources on Tomcat 8.
No problem with Tomcat 7.
It looks like this issue for another filter: http://www.fusion-reactor.com/support/kb/frs-339/

thanks
Arnaud

**Comment by magnayn** [comment]
I can confirm this behaviour. Basically your client sits waiting for the number of bytes specified in the Content-Length header.

I've switched to turning compression on in the Tomcat 8 connector server.xml, e.g:

```
  <Connector port="8888" protocol="HTTP/1.1" 
      compression="on"
      compressionMinSize="2048" 
      compressableMimeType="application/x-amf, application/x-shockwave-flash, text/html"
      connectionTimeout="20000" redirectPort="8443" URIEncoding="UTF-8" />
```

I think if you want to fix ziplet, it needs to remove the Content-Length header if it's going to gzip the response.

**Comment by ziplet** [comment]
We are open to receive PR to fix this. Please include tests :)

**Comment by abstratt** [comment]
Another troubled user here. Steps:

1. Run your Grails app using ziplet and Tomcat 8 (using grails run-app, or deploying to the app server)
2. Access a static resource that is handled by ziplet and it gets stuck:

```
wget -S --header 'Accept-Encoding: gzip,deflate' http://localhost:8090/clarity/lib/lightbox/css/lightbox.css

--2015-10-07 22:33:51--  http://localhost:8090/myapp/lib/lightbox/css/lightbox.css
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: Apache-Coyote/1.1
  Vary: Accept-Encoding
  Accept-Ranges: bytes
  ETag: W/"3981-1444245888000"-gzip
  Last-Modified: Wed, 07 Oct 2015 19:24:48 GMT
  Content-Encoding: gzip
  Content-Type: text/css
  Content-Length: 3981
  Date: Thu, 08 Oct 2015 01:33:51 GMT
Length: 3981 (3,9K) [text/css]
Saving to: ‘lightbox.css.3’

26% [==========================>                                                                            ] 1.047       --.-K/s  eta 21s
```

where 3981 is the uncompressed length, and 1.047 is the compressed length.

With Tomcat 7, the output is different:

```
wget -S --header 'Accept-Encoding: gzip,deflate' http://localhost:9080/clarity/lib/lightbox/css/lightbox.css
--2015-10-08 01:53:45--  http://localhost:9080/clarity/lib/lightbox/css/lightbox.css
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:9080... failed: Connection refused.
Connecting to localhost|127.0.0.1|:9080... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: Apache-Coyote/1.1
  Vary: Accept-Encoding
  Accept-Ranges: bytes
  ETag: W/"3981-1430175884000"-gzip
  Last-Modified: Mon, 27 Apr 2015 23:04:44 GMT
  Content-Encoding: gzip
  Content-Type: text/css
  Date: Thu, 08 Oct 2015 01:53:45 GMT
  Connection: close
Length: unspecified [text/css]
Saving to: “lightbox.css.1”

    [ <=>                                                                                                   ] 1.047       --.-K/s   in 0,001s 
```

**Comment by abstratt** [comment]
Dropping ziplet, and turning Tomcat 8 compression on, the problem does not occur:

```
wget -S --header 'Accept-Encoding: gzip,deflate' http://localhost:19080/clarity/lib/lightbox/css/lightbox.css
--2015-10-07 23:28:30--  http://localhost:19080/clarity/lib/lightbox/css/lightbox.css
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:19080... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: Apache-Coyote/1.1
  Set-Cookie: JSESSIONID=113555C7D655DBE65BE39B17DFF5D6B7; Path=/; HttpOnly
  Accept-Ranges: bytes
  ETag: W/"3981-1430243748000"
  Last-Modified: Tue, 28 Apr 2015 17:55:48 GMT
  Content-Type: text/css
  Transfer-Encoding: chunked
  Content-Encoding: gzip
  Vary: Accept-Encoding
  Date: Thu, 08 Oct 2015 02:28:30 GMT
Length: unspecified [text/css]
Saving to: ‘lightbox.css.6’

    [ <=>                                                                                                   ] 1.047       --.-K/s   in 0,002s
```

Notice the length is unspecified.

**Comment by jordandev** [comment]
Same problem here. Can't use this filter.

**Comment by fgaule** [comment]
I'll be not able to spend time developing a fix for a while :( . In case any of you is able to send a PR i will buy some time to check it out and merge it

**Comment by oosterholt** [comment]
Probably has something to do with the fact `servlet api V3.1` introduced `setContentLengthLong()`.
Found other compression filters ([here](https://github.com/oblac/jodd/issues/189) and [here](https://github.com/omnifaces/omnifaces/blob/master/src/main/java/org/omnifaces/servlet/GzipHttpServletResponse.java)) which doesn't set the "Content-Length" header at all and just overloads both `setContentLength()` and `setContentLengthLong()` with no implementation (seems [to be OK](http://stackoverflow.com/a/8797893/1183010)].

Hope this info helps.

**Comment by fgaule** [comment]
I have recently merged a fix #13 for this issue thanks to @oosterholt. Now it is on master, so you can make a local snapshot to test it or wait me to light a SNAPSHOT version during this week (or weekend). 
After we all know it is working for you guys, i will be doing a release :smile:

**Comment by fgaule** [comment]
Did that fix solve your issues?

**Comment by sergystepanov** [comment]
It fixed huge latency on Tomcat 8 & 9 for me/

**Comment by fgaule** [comment]
Version 2.1.2 has been released
